//! Static-byte slices for the embedded embedder model, generated by `build.rs`.
//!
//! When the `native-embedder` feature is active and the build host has the
//! selected model in its HuggingFace cache, `build.rs` writes an
//! `embedded_embedder_data.rs` file with `include_bytes!` pointing at the
//! cache snapshot. Otherwise, empty slices are shipped and the runtime path
//! falls back to an HF-cache lookup.
//!
//! Vibecrafted with AI Agents by VetCoders (c)2026 VetCoders

#[cfg(aicx_embed_embedder)]
mod data {
    include!(concat!(env!("OUT_DIR"), "/embedded_embedder_data.rs"));
}

#[cfg(not(aicx_embed_embedder))]
mod data {
    pub static CONFIG: &[u8] = &[];
    pub static TOKENIZER: &[u8] = &[];
    pub static WEIGHTS: &[u8] = &[];
    pub static REPO: &str = "";
}

/// Static view of an embedded embedder model (bytes live in the binary).
pub struct EmbeddedModel {
    pub config: &'static [u8],
    pub tokenizer: &'static [u8],
    pub weights: &'static [u8],
    pub repo: &'static str,
}

impl EmbeddedModel {
    /// Total size in bytes across the three shipped artifacts.
    pub fn total_size(&self) -> usize {
        self.config.len() + self.tokenizer.len() + self.weights.len()
    }
}

/// Returns true when `build.rs` managed to seal a usable embedder into the binary.
pub fn is_embedded_available() -> bool {
    cfg!(aicx_embed_embedder) && !data::WEIGHTS.is_empty()
}

/// Fetch embedded model byte slices if available.
pub fn get_embedded() -> Option<EmbeddedModel> {
    if !is_embedded_available() {
        return None;
    }
    Some(EmbeddedModel {
        config: data::CONFIG,
        tokenizer: data::TOKENIZER,
        weights: data::WEIGHTS,
        repo: data::REPO,
    })
}

/// Best-effort static dimension hint parsed from the embedded config.
///
/// Returns `None` if no embedded model was shipped or if the config is not
/// JSON-parseable at lookup time. Runtime load fills in the real dimension.
pub fn embedded_dimension() -> Option<usize> {
    if !is_embedded_available() {
        return None;
    }
    let raw = std::str::from_utf8(data::CONFIG).ok()?;
    let parsed: serde_json::Value = serde_json::from_str(raw).ok()?;
    parsed
        .get("hidden_size")
        .and_then(|v| v.as_u64())
        .map(|v| v as usize)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_total_size_matches_slices() {
        if let Some(model) = get_embedded() {
            assert_eq!(
                model.total_size(),
                model.config.len() + model.tokenizer.len() + model.weights.len()
            );
        }
    }
}
